--- #YAML:1.0
name: Pipe-Tube-Csv
version: 0.01
author:
  - Gabor Szabo <gabor@pti.co.il>
abstract: Csv processor tube in Pipe
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
