---
abstract: unknown
author:
  - 'Gabor Szabo <gabor@szabgab.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pipe-Tube-Csv
no_index:
  directory:
    - t
    - inc
requires:
  Pipe: 0.03
  Test::More: 0.47
  Text::CSV_XS: 0.23
resources:
  repository: https://github.com/szabgab/Pipe-Tube-Csv
version: 0.02
